### PR TITLE
updating my develop branche

### PR DESCRIPTION
**Pull request by RHITNL**

### CODE REVIEW

**Comment by alexinman** [comment]
What is this for? It looks like it has all the changes I made already. 
Are you trying to update your develop branch?
If so, here is how you can do it:
http://stackoverflow.com/questions/7244321/how-do-i-update-a-github-forked-repository

**Comment by RHITNL** [comment]
Yeah sorry,

my dev-rhitnl branche had a lot of own created code which ran live on my server and was backuped in github. There where to many changes so a merge was not possible. My develop branche was outdated and had also own changes (made before dev-rhitnl was created). Now my develop branche is simular to yours and my dev-rhitnl is a playground with your last changes.

**Comment by alexinman** [comment]
Try rebasing your branch against alexinman:develop
That link I provided explains it pretty good. 
I don't think this PR is needed. Ok with me closing it?

**Comment by RHITNL** [comment]
sure! Git is bit new to me although I have my own gitlab running

**Pull request closed without merging**
